=== saurabhchachra/saurabhchachra.github.io/restaurants.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT education (program+)>
<!ELEMENT program (University, Degree, Year)>
<!ELEMENT University (#PCDATA)>
<!ELEMENT Degree (#PCDATA)>
<!ELEMENT Year (#PCDATA)>

=== saurabhchachra/saurabhchachra.github.io/restaurants.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE education SYSTEM "restaurants.dtd">
<education>
  <program>
    <University>University of California, Berkeley</University>
    <Degree>Master's in Information</Degree>
    <Year>2022 - 2024 (expected)</Year>
  </program>
  <program>
    <University>University of California, Berkeley</University>
    <Degree>Post Baccalaureate Certificate in Psychology</Degree>
    <Year>2019 - 2021</Year>
  </program>
  <program>
    <University>Kurukshetra University, Kurukshetra</University>
    <Degree>Bachelor in Business Administration</Degree>
    <Year>2010 - 2013</Year>
  </program>
</education>
